/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_timmyovo_nspasteboard_NSPasteboardAPI */

#ifndef _Included_com_github_timmyovo_nspasteboard_NSPasteboardAPI
#define _Included_com_github_timmyovo_nspasteboard_NSPasteboardAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_timmyovo_nspasteboard_NSPasteboardAPI
 * Method:    clearContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_timmyovo_nspasteboard_NSPasteboardAPI_clearContent
(JNIEnv* env, jclass);

/*
 * Class:     com_github_timmyovo_nspasteboard_NSPasteboardAPI
 * Method:    getClipboardContent
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_timmyovo_nspasteboard_NSPasteboardAPI_getClipboardContent
(JNIEnv* env, jclass, jint type);

/*
 * Class:     com_github_timmyovo_nspasteboard_NSPasteboardAPI
 * Method:    writeClipboardString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_timmyovo_nspasteboard_NSPasteboardAPI_writeClipboardString
(JNIEnv* env, jclass, jstring s);

/*
 * Class:     com_github_timmyovo_nspasteboard_NSPasteboardAPI
 * Method:    writeClipboardFileURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_timmyovo_nspasteboard_NSPasteboardAPI_writeClipboardFileURL
(JNIEnv* env, jclass, jstring url);

JNIEXPORT void JNICALL Java_com_github_timmyovo_nspasteboard_NSPasteboardAPI_writeClipboardFilesURL
 (JNIEnv *env, jclass, jobjectArray urls);

#ifdef __cplusplus
}
#endif
#endif
